# Generated by Django 3.1.3 on 2021-08-09 11:05

from django.db import migrations, models
import scapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('scapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=scapi.models.generateUniqueCode, max_length=8, unique=True),
        ),
    ]
